SMS/Models/SetupViewModel/SetupServiceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SMS.Models.SetupViewModel
{
    public class SetupServiceViewModel
    {
        public int ServiceId { get; set; }
        [Required(ErrorMessage ="Service Name is required")]
        [Display(Name ="Service Name")]
        public string ServiceName { get; set; }
        public int? ServiceOrder { get; set; }
        public bool Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        public int? DeletedBy { get; set; }
        public List<SetupServiceViewModel> SetupServiceViewModelList { get; set; }

    }
}

SMS/Controllers/SetupServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Models.SetupViewModel;
using SMS.Service.Providers.SetupProviders;
using SMS.Utilities;

namespace SMS.Controllers
{
    [CustomAuthorize(Roles = "SuperAdmin,Admin")]
    public class SetupServiceController : Controller
    {
        private readonly ISetupServiceProvider _pro;
        public SetupServiceController()
        {
            this._pro = new SetupServiceProvider();
        }
            
        public ActionResult Index()
        {
            SetupServiceViewModel model = new SetupServiceViewModel();
            model = _pro.GetServiceList();
            return View(model);
        }
        public ActionResult Create()
        {
            SetupServiceViewModel model = new SetupServiceViewModel();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SetupServiceViewModel model)
        {
            int conditionApply = 1;
            if (!ModelState.IsValid)
            {
                TempData["validationError"] = Utilities.ValidationMessage.validationError;
                return RedirectToAction("Index");
            }
            else
            {
                conditionApply = _pro.Save(model);

                if (conditionApply == 2)
                {
                    TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
                }

                else if (conditionApply == 1)
                {
                    TempData["save"] = Utilities.ValidationMessage.save;
                }
                else if (conditionApply == 0)
                {
                    TempData["savefailed"] = Utilities.ValidationMessage.savefailed;
                }
            }

            return RedirectToAction("Index");
           
        }
        public ActionResult Edit(int? id)
        {
            SetupServiceViewModel model = new SetupServiceViewModel();
            if (id >0)
            {
                model = _pro.Edit(id ?? 0);
            }
            
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SetupServiceViewModel model)
        {

            int condiontApply = 0;
            if (ModelState.IsValid)
            {
                condiontApply = _pro.Save(model);
            }
            if (condiontApply == 1)
            {
                TempData["save"] = Utilities.ValidationMessage.edit;
            }
            else if (condiontApply == 2)
            {
                TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
            }
            else
            {
                TempData["savefailed"] = Utilities.ValidationMessage.editfailed;
            }

            return RedirectToAction("Index");

        }
        public ActionResult Delete(int? id)
        {
            int condiontApply = 0;
            condiontApply = _pro.Delete(id ?? 0);
            if (condiontApply == 1)
            {
                TempData["save"] = Utilities.ValidationMessage.delete;
            }
            else
            {
                TempData["savefailed"] = Utilities.ValidationMessage.deletefailed;
            }
            return RedirectToAction("Index");
        }
    }
}

SMS/Views/SetupService/Create.cshtml
@model SMS.Models.SetupViewModel.SetupServiceViewModel
@{
    Layout = null;
}

<div class="modal-dialog"style="margin-left:35%;">
    <div class="modal-content"style="width:500px !important">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="addService">
                <strong>Add New Service</strong>
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Create", "SetupService", FormMethod.Post))
            {    @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model=>model.ServiceId)

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Service Name<span style="color:red">*</span></label></div>
                        <div class="col-xs-12">
                          @Html.TextBoxFor(model => model.ServiceName, new { @class = "form-control", @placeholder = "Service Name" })
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Service Order<span style="color:red">*</span></label></div>
                        <div class="col-xs-12">
                            @Html.TextBoxFor(model => model.ServiceOrder, new { @class = "form-control", @placeholder = "Service Name" })
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            }
        </div>
    </div>
</div>

SMS/Views/SetupService/Edit.cshtml
@model SMS.Models.SetupViewModel.SetupServiceViewModel
@{
    Layout = null;
}

<div class="modal-dialog"style="margin-left:35%;">
    <div class="modal-content"style="width:500px !important">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="editService">
                <strong>Update Service</strong>
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Create", "SetupService", FormMethod.Post))
            {    @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ServiceId)


                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Service Name<span style="color:red">*</span></label></div>
                        <div class="col-xs-12">
                            @Html.TextBoxFor(model => model.ServiceName, new { @class = "form-control", @placeholder = "Service Name" })
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Service Order<span style="color:red">*</span></label></div>
                        <div class="col-xs-12">
                            @Html.TextBoxFor(model => model.ServiceOrder, new { @class = "form-control", @placeholder = "Service Name" })
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Status</label></div>
                        <div class="col-xs-12">
                            @Html.CheckBoxFor(model => model.Status)
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Update" />
                </div>
            }
        </div>
    </div>
</div>

SMS/Views/SetupService/Index.cshtml
@model SMS.Models.SetupViewModel.SetupServiceViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int i = 1;
}
<link href="~/Content/skins/flat/green.css" rel="stylesheet" />
@if (TempData["validationError"] != null)
{
    <div class="alert alert-danger">
        @TempData["validationError"]
    </div>
}

@if (TempData["AlreadyExits"] != null)
{
    <div class="alert alert-danger">
        @TempData["AlreadyExits"]
    </div>
}

@if (TempData["savefailed"] != null)
{
    <div class="alert alert-danger">
        @TempData["savefailed"]
    </div>
}

@if (TempData["save"] != null)
{
    <div class="alert alert-success">
        @TempData["save"]
    </div>
}
<div class="main-content">
    <div class='row r-below-header'>
        <div class='col-md-8 col-sm-12'>
            <div class="r-page-title">
                <h1>
                 Service List
                </h1>
            </div>
        </div>
    </div>
</div>

<input type="button" value="Add New" onclick="addNew('#add-service', 'Create', 'SetupService')" class="btn btn-primary" />
<div class="clearfix"></div>

<table class="table table-responsive table-striped jambo_table bulk_action">
    <thead>
        <tr class="headings">
            <th><input type="checkbox" class="flat" name="table_records"></th>
            <th class="column-title"> S.N.</th>
            <th class="column-title">Service Name </th>
            <th class="column-title">Service Order </th>
            <th class="column-title">Status </th>
            <th class="column-title no-link last">
                <span class="nobr" style="width:110px">Action</span>
            </th>
            <th class="bulk-actions" colspan="7">
                <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.SetupServiceViewModelList)
            {
            <tr class="even pointer">
                <td class="a-center ">
                    <input type="checkbox" class="flat" name="table_records">
                </td>
                <td>@i</td>
                <td>@item.ServiceName</td>
                <td>@item.ServiceOrder</td>
                <td>@item.Status</td>
                <td style="width:110px">
                    <button class="btn btn-primary" onclick="update(@item.ServiceId,'#update-service','Edit','SetupService')"><span class="fa fa-edit"></span></button>

                    <button class="btn btn-danger" onclick="deleteRow(@item.ServiceId,'@item.ServiceName','Delete','SetupService')"><span class="fa fa-trash"></span></button>
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>


<div class="modal fade" id="add-service" tabindex="-1" role="dialog" aria-labelledby="addService">
    @{Html.RenderAction("Create", "SetupService");}
</div>

<div class="modal fade" id="update-service" tabindex="-1" role="dialog" aria-labelledby="editService">
    @{Html.RenderAction("Edit", "SetupService");}
</div>

<div class="modal fade" id="delete-conformation" tabindex="-1" role="dialog" aria-labelledby="deleteconformation">
    @{Html.RenderAction("DeleteConformation", "CommonAjaxRequest");}
</div>