SMS/Models/SetupViewModel/SetupFacultyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SMS.Models.SetupViewModel
{
    public class SetupFacultyViewModel
    {
        public int FacultyId { get; set; }
        public int ClassId { get; set; }
        public string  ClassName { get; set; }
        [Required(ErrorMessage ="Faculty Name is required")]
        [Display(Name ="Faculty Name")]
        public string FacultyName { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public DateTime DeletedDate { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public int DeletedBy { get; set; }   

        public SetupClassViewModel ObjSetupClassViewModel { get; set; }
        public List<SetupFacultyViewModel> SetupFacultyViewModelList { get; set; }
    }
}

SMS/Controllers/SetupFacultyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Service.Providers.SetupFacultyProvider;
using SMS.Models.SetupViewModel;
using SMS.Utilities;

namespace SMS.Controllers
{
    //[CustomAuthorize(Roles = "SuperAdmin,Admin")]
    public class SetupFacultyController : Controller
    {
        // GET: SetupFaculty
        private readonly SetupFacultyProvider _pro;
        public SetupFacultyController()
        {
            this._pro = new SetupFacultyProvider();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _GetFacultyList(string name)
        {
            SetupFacultyViewModel model = new SetupFacultyViewModel();
            model = _pro.GetList(name);
            return View(model);
        }
        public ActionResult Create()
        {
            SetupFacultyViewModel model = new SetupFacultyViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(SetupFacultyViewModel model)
        {

            int conditionApply = 1;
            if (!ModelState.IsValid)
            {
                TempData["validationError"] = Utilities.ValidationMessage.validationError;

                return Json(Utilities.ValidationMessage.validationError, JsonRequestBehavior.AllowGet);
                // return RedirectToAction("Index");
            }
            else
            {
                conditionApply = _pro.Save(model);

                if (conditionApply == 2)
                {
                    //TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
                    return Json(Utilities.ValidationMessage.AlreadyExits, JsonRequestBehavior.AllowGet);

                }

                else if (conditionApply == 1)
                {
                    //TempData["save"] = Utilities.ValidationMessage.save;
                    return Json(Utilities.ValidationMessage.save, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    //TempData["savefailed"] = Utilities.ValidationMessage.savefailed;
                    return Json(Utilities.ValidationMessage.savefailed, JsonRequestBehavior.AllowGet);
                }
            }
            // return View(model);

            //return Json(data, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Edit(int? id)
        {
            SetupFacultyViewModel model = new SetupFacultyViewModel();
            model = _pro.Edit(id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(SetupFacultyViewModel model)
        {
            int condiontApply = 0;
            if (ModelState.IsValid)
            {
                condiontApply = _pro.Save(model);
            }
            if (condiontApply == 1)
            {
                // TempData["save"] = Utilities.ValidationMessage.edit;
                return Json(Utilities.ValidationMessage.edit, JsonRequestBehavior.AllowGet);
            }
            else if (condiontApply == 2)
            {
                //TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
                return Json(Utilities.ValidationMessage.AlreadyExits, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //TempData["savefailed"] = Utilities.ValidationMessage.editfailed;
                return Json(Utilities.ValidationMessage.editfailed, JsonRequestBehavior.AllowGet);
            }

            // return RedirectToAction("Index");
        }
        public JsonResult Delete(int? id)
        {
            int condiontApply = 0;
            condiontApply = _pro.Delete(id ?? 0);
            if (condiontApply == 1)
            {
                //TempData["save"] = Utilities.ValidationMessage.delete;
                return Json(Utilities.ValidationMessage.delete, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //TempData["savefailed"] = Utilities.ValidationMessage.deletefailed;
                return Json(Utilities.ValidationMessage.deletefailed, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

SMS/Views/SetupFaculty/Create.cshtml
@model SMS.Models.SetupViewModel.SetupFacultyViewModel

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<form id="setupFaculty">
    <div class="modal-dialog" style="width:500px !important ; margin-left: auto">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="addFaculty">
                    <strong> Add New Faculty</strong>
                </h4>
            </div>
            <div class="modal-body" id="facultyCreate">

                @*@using (Ajax.BeginForm("Create", "SetupFaculty", new AjaxOptions() { UpdateTargetId = "ajaxform" }))
                    {*@
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Select Class</label></div>
                        <div class="col-xs-12">
                            @Html.DropDownListFor(model => model.ClassId, SMS.Utilities.CommonUtilities.GetClassList(), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClassId)
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Faculty Name<span style="color:red">*</span></label></div>
                        <div class="col-xs-12">
                            @Html.TextBoxFor(model => model.FacultyName, htmlAttributes: new { @class = "form-control", @placeholder = "Faculty Name", @id = "facultyname", @name = "facultyname" })
                            @Html.ValidationMessageFor(model => model.FacultyName)
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="button" class="btn btn-primary" value="Save" onclick="postData('#setupFaculty', '#add-faculty', 'Create', 'SetupFaculty', '#faultList', '_GetFacultyList')" />
                </div>

                @* } *@
            </div>
        </div>
    </div>
</form>

SMS/Views/SetupFaculty/Edit.cshtml
@model SMS.Models.SetupViewModel.SetupFacultyViewModel

<form id="setupFaculty">
    <div class="modal-dialog" style="width:500px !important ; margin-left: auto">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="editFaculty">
                    <strong>Update Faculty</strong>
                </h4>
            </div>
            <div class="modal-body">
                @*@using (Html.BeginForm("Edit", "SetupFaculty", FormMethod.Post))
                    {*@

                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()

                @Html.HiddenFor(model => model.FacultyId)

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Select Class</label></div>
                        <div class="col-xs-12">
                            @Html.DropDownListFor(model => model.ClassId, SMS.Utilities.CommonUtilities.GetClassList(), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClassId)
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Faculty Name<span style="color:red">*</span></label></div>
                        <div class="col-xs-12">
                            @Html.TextBoxFor(model => model.FacultyName, htmlAttributes: new { @class = "form-control", @placeholder = "Faculty Name", @id = "facultyname", @name = "facultyname" })
                            @Html.ValidationMessageFor(model => model.FacultyName)
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Status</label></div>
                        <div class="col-xs-12">
                            @Html.CheckBoxFor(model => model.Status)
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="button" class="btn btn-primary" value="Update" onclick="postData('#setupFaculty', '#update-faculty', 'Edit', 'SetupFaculty', '#faultList', '_GetFacultyList')" />
                    @*<input type="submit" class="btn btn-primary" value="Update" />*@
                </div>
                @*}*@
            </div>
        </div>
    </div>
</form>

SMS/Views/SetupFaculty/Index.cshtml
@{
    ViewBag.Title = "Faculty List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<script src="~/Scripts/jquery-2.1.0.min.js"></script>

<link href="~/Content/skins/flat/green.css" rel="stylesheet" />

<div class="main-content">
    <div class='row r-below-header'>
        <div class='col-md-8 col-sm-12'>
            <div class="r-page-title">
                <h1>
                    Faculty List
                </h1>
            </div>
            <div id="form_errors"></div>
        </div>
    </div>
</div>

<div class="form-gr">
    <div class="col-sm-6">
        <input type="button" value="Add New" onclick="addNew('#add-faculty', 'Create', 'SetupFaculty')" class="btn btn-primary" />
    </div>
    <div class="col-sm-6">
        <input type="text" class="form-control" id="faultyNameId" onclick="search($('#faultyNameId').val(), '#faultList', '_GetFacultyList', 'SetupFaculty');" />
    </div>
</div>
<div class="clearfix"></div>
<div class="table table-responsive">
    <div id="faultList"></div>
</div>

<div class="modal fade" id="add-faculty" tabindex="-1" role="dialog" aria-labelledby="addFaculty">
    @{Html.RenderAction("Create", "SetupFaculty");}
</div>

<div class="modal fade" id="update-faculty" tabindex="-1" role="dialog" aria-labelledby="editfaculty">
    @{Html.RenderAction("Edit", "SetupFaculty");}
</div>
<div class="modal fade" id="delete-conformation" tabindex="-1" role="dialog" aria-labelledby="deleteconformation">
    @{Html.RenderAction("DeleteConformation", "CommonAjaxRequest");}
</div>

<script>
    $(document).ready(function (e) {
        search($('#faultyNameId').val(), '#faultList', '_GetFacultyList', 'SetupFaculty');
    });
</script>

SMS/Views/SetupFaculty/_GetFacultyList.cshtml
@model SMS.Models.SetupViewModel.SetupFacultyViewModel
@{
    int i = 1;
}
<div id="facultiListId">


    <table class="table table-striped jambo_table bulk_action">
        <thead>
            <tr class="headings">
                <th><input type="checkbox" class="flat" name="table_records"></th>
                <th class="column-title">S.N.</th>
                <th class="column-title">Class Name </th>
                <th class="column-title">Faculty Name </th>
                <th class="column-title">Status </th>
                <th class="column-title no-link last">
                    <span class="nobr" style="width:110px">Action</span>
                </th>
                <th class="bulk-actions" colspan="7">
                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.SetupFacultyViewModelList)
            {
                <tr class="even pointer">
                    <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                    </td>
                    <td>@i</td>
                    <td>@item.ClassName</td>
                    <td>@item.FacultyName</td>
                    <td>@item.Status</td>
                    <td style="width:110px">
                        <button class="btn btn-primary" onclick="update(@item.FacultyId,'#update-faculty','Edit','SetupFaculty')"><span class="fa fa-edit"></span></button>
                        <button class="btn btn-danger" onclick="deleteRow(@item.FacultyId,'@item.FacultyName','Delete','SetupFaculty','_GetFacultyList','#faultList')"><span class="fa fa-trash"></span></button>
                    </td>
                </tr>
                i++;
            }

        </tbody>
    </table>

</div>