SMS/Models/SetupViewModel/SetupDepartmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SMS.Models.SetupViewModel
{
    public class SetupDepartmentViewModel
    {
        public int DepartmentId { get; set; }
        [Required(ErrorMessage = "Department Name is Required")]
        [Display(Name = "Department Name")]
        public string DepartmentName { get; set; }
        public bool Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        public int? DeletedBy { get; set; }
        public List<SetupDepartmentViewModel> SetupDepartmentViewModelList { get; set; }
    }
}

SMS/Controllers/SetupDepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Models.SetupViewModel;
using SMS.Service.Providers.SetupProviders;
using SMS.Utilities;

namespace SMS.Controllers
{
    [CustomAuthorize(Roles = "SuperAdmin,Admin")]
    public class SetupDepartmentController : Controller
    {
        private readonly ISetupDepartmentProvider _setupDepartmentProvider;
        public SetupDepartmentController()
        {
            _setupDepartmentProvider = new SetupDepartmentProvider();
        }
        public ActionResult Index()
        {
            SetupDepartmentViewModel model = new SetupDepartmentViewModel();
            model = _setupDepartmentProvider.GetDepartmentList();
            return View(model);
        }
        public ActionResult Create()
        {
            SetupDepartmentViewModel model = new SetupDepartmentViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(SetupDepartmentViewModel model)
        {
            int conditionApply = 1;
            if (!ModelState.IsValid)
            {
                TempData["validationError"] = Utilities.ValidationMessage.validationError;
                return RedirectToAction("Index");
            }
            else
            {
                conditionApply = _setupDepartmentProvider.Save(model);

                if (conditionApply == 2)
                {
                    TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
                }
                else if (conditionApply == 0)
                {
                    TempData["savefailed"] = Utilities.ValidationMessage.savefailed;
                }
                else if (conditionApply == 1)
                {
                    TempData["save"] = Utilities.ValidationMessage.save;
                }
            }

            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            SetupDepartmentViewModel model = new SetupDepartmentViewModel();
            if (id > 0)
            {
                model = _setupDepartmentProvider.Edit(id ?? 0);
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(SetupDepartmentViewModel model)
        {
            int condiontApply = 0;
            if (ModelState.IsValid)
            {
                condiontApply = _setupDepartmentProvider.Save(model);
            }
            if (condiontApply == 1)
            {
                TempData["save"] = Utilities.ValidationMessage.edit;
            }
            else if (condiontApply == 2)
            {
                TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
            }
            else
            {
                TempData["savefailed"] = Utilities.ValidationMessage.editfailed;
            }

            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            int condiontApply = 0;
            condiontApply = _setupDepartmentProvider.Delete(id ?? 0);
            if (condiontApply == 1)
            {
                TempData["save"] = Utilities.ValidationMessage.delete;
            }
            else
            {
                TempData["savefailed"] = Utilities.ValidationMessage.deletefailed;
            }

            return RedirectToAction("Index");
        }
    }
}

SMS/Views/SetupDepartment/Create.cshtml
@model SMS.Models.SetupViewModel.SetupDepartmentViewModel
<div class="modal-dialog"style="margin-left:35%;">
    <div class="modal-content" style="width:500px !important">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="addDepartment">
               <strong>Add New Department</strong> 
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Create", "SetupDepartment", FormMethod.Post))
            {    @Html.ValidationSummary(true)
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label>
                                Department Name<span style="color:red">*</span>
                            </label>
                            @Html.TextBoxFor(model => model.DepartmentName, new { @class = "form-control" ,@placeholder="Department Name"})
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            }
        </div>
    </div>
</div>

SMS/Views/SetupDepartment/Edit.cshtml
@model SMS.Models.SetupViewModel.SetupDepartmentViewModel
<div class="modal-dialog"style="margin-left:35%;">
    <div class="modal-content"style="width:500px !important">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="editDepartment">
               <strong>Update Department</strong>
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Edit", "SetupDepartment", FormMethod.Post))
            {    @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.DepartmentId)

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label>Department Name</label></div>
                        <div class="col-xs-12">
                           @Html.TextBoxFor(model => model.DepartmentName, new { @class = "form-control", @placeholder = "Department Name" })
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 form-group">
                    <div class="row">
                        <div class="col-xs-12"><label> Status</label></div>
                        <div class="col-xs-12">
                            @Html.CheckBoxFor(model => model.Status)
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
               
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Update" />
                </div>
            }
        </div>
    </div>
</div>

SMS/Views/SetupDepartment/Index.cshtml
@model SMS.Models.SetupViewModel.SetupDepartmentViewModel
@{
    ViewBag.Title = "Department List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int i = 1;
}

<link href="~/Content/skins/flat/green.css" rel="stylesheet" />

@if (TempData["validationError"] != null)
{
    <div class="alert alert-danger">
        @TempData["validationError"]
    </div>
}

@if (TempData["AlreadyExits"] != null)
{
    <div class="alert alert-danger">
        @TempData["AlreadyExits"]
    </div>
}

@if (TempData["savefailed"] != null)
{
    <div class="alert alert-danger">
        @TempData["savefailed"]
    </div>
}

@if (TempData["save"] != null)
{
    <div class="alert alert-success">
        @TempData["save"]
    </div>
}
<div class="main-content">
    <div class='row r-below-header'>
        <div class='col-md-8 col-sm-12'>
            <div class="r-page-title">
                <h1>
                    Department List
                </h1>
            </div>
        </div>
    </div>
</div>

<input type="button" value="Add New" onclick="addNew('#add-department','Create','SetupDepartment')" class="btn btn-primary" />
<div class="clearfix"></div>
<div class="table table-responsive">
    <table class="table table-striped jambo_table bulk_action">
        <thead>
            <tr class="headings">
                <th class="column-title">S.N </th>
                <th class="column-title">DepartmentName </th>
                <th class="column-title">Status </th>
                <th class="column-title no-link last">
                    <span class="nobr" style="width:110px;">Action</span>
                </th>
                <th class="bulk-actions" colspan="7">
                        <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                    </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.SetupDepartmentViewModelList)
            {
                <tr class="even pointer">
                    <td>@i</td>
                    <td>@item.DepartmentName</td>
                    <td>@item.Status</td>
                    <td style="width:110px;">
                        <button class="btn btn-primary" onclick="update(@item.DepartmentId,'#update-department','Edit','SetupDepartment')"><span class="fa fa-edit"></span></button>
                        <button class="btn btn-danger" onclick="deleteRow(@item.DepartmentId,'@item.DepartmentName','Delete','SetupDepartment')"><span class="fa fa-trash"></span></button>
                    </td>

                </tr>
                i++;
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="add-department" tabindex="-1" role="dialog" aria-labelledby="addDepartment">
    @{Html.RenderAction("Create", "SetupDepartment");}
</div>

<div class="modal fade" id="update-department" tabindex="-1" role="dialog" aria-labelledby="editDepartment">
    @{Html.RenderAction("Edit", "SetupDepartment");}
</div>

<div class="modal fade" id="delete-conformation" tabindex="-1" role="dialog" aria-labelledby="deleteconformation">
    @{Html.RenderAction("DeleteConformation", "CommonAjaxRequest");}
</div>