SMS/Models/StudentExamViewModel/MarkSheetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SMS.Models.MarkSheetViewModel
{
    public class MarkSheetViewModel
    {
        public int MarkSheetId { get; set; }
        public int? TerminalExamId { get; set; }
        public string TerminalExamName { get; set; }
        public int? StudentId { get; set; }
        public string StudentName { get; set; }
        public string ClassName { get; set; }
        
        public int? ClassId { get; set; }
        public string FacultyName { get; set; }
        public int? FacultyId { get; set; }
        public string SectionName { get; set; }
        public int? SectionId { get; set; }
        public string SubjectName { get; set; }
        public int? SubjectId { get; set; }
        public decimal? ObtainThroryMarks { get; set; }
        public decimal? ObtainPracticalMarks { get; set; }
        public decimal? ObtainTotalMarks { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public List<MarkSheetViewModel> MarkSheetViewModelList { get; set; }

    }
}

SMS/Controllers/MarkSheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Service.Providers.MarkSheetProviders;
using SMS.Models.MarkSheetViewModel;

namespace SMS.Controllers
{
    public class MarkSheetController : Controller
    {
        private readonly IMarkSheetProvider _markSheetProvider;
        public MarkSheetController()
        {
            this._markSheetProvider = new MarkSheetProvider();
        }
        public ActionResult Index()
        {
            MarkSheetViewModel model = new MarkSheetViewModel();
            model = _markSheetProvider.GetMarkSheetList();
            return View(model);
        }
        public ActionResult Create()
        {
            MarkSheetViewModel model = new MarkSheetViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(MarkSheetViewModel model)
        {
            int conditionApply = 1;
            if (!ModelState.IsValid)
            {
                TempData["validationError"] = Utilities.ValidationMessage.validationError;
                return RedirectToAction("Index");
            }
             conditionApply = _markSheetProvider.Save(model);
            if (conditionApply == 0)
            {
                TempData["savefailed"] = Utilities.ValidationMessage.savefailed;
            }
            else if (conditionApply == 2)
            {
                TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
            }
            else
            {
                TempData["save"] = Utilities.ValidationMessage.save;

            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            MarkSheetViewModel model = new MarkSheetViewModel();
            model = _markSheetProvider.Edit(id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(MarkSheetViewModel model)
        {
            int conditionApply = 0;
            if (ModelState.IsValid)
            {
                conditionApply = _markSheetProvider.Save(model);
            }
            if (conditionApply == 1)
            {
                TempData["save"] = Utilities.ValidationMessage.edit;
            }
            else if (conditionApply == 2)
            {
                TempData["AlreadyExits"] = Utilities.ValidationMessage.AlreadyExits;
            }
            else
            {
                TempData["savefailed"] = Utilities.ValidationMessage.editfailed;
            }



            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            int condiontApply = 0;
            condiontApply = _markSheetProvider.Delete(id ?? 0);

            if (condiontApply == 1)
            {
                TempData["save"] = Utilities.ValidationMessage.delete;
            }
            else
            {
                TempData["savefailed"] = Utilities.ValidationMessage.deletefailed;
            }

            return RedirectToAction("Index");
        }
    }
}

SMS/Views/MarkSheet/Create.cshtml
@model SMS.Models.MarkSheetViewModel.MarkSheetViewModel
<div class="modal-dialog"style="margin-left:35%">
    <div class="modal-content"style="width:500px!important">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="addMarkSheet">
                 Create MarkSheet
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Create", "MarkSheet", FormMethod.Post))
            {    @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Student Name</label>
                            @Html.DropDownListFor(model => model.StudentId, SMS.Utilities.CommonUtilities.GetStudentList(), new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Terminal Exam Name</label>
                            @Html.DropDownListFor(model => model.TerminalExamId, SMS.Utilities.CommonUtilities.GetTerminaExamlList(), new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Class Name</label>
                            @Html.DropDownListFor(model => model.ClassId, SMS.Utilities.CommonUtilities.GetClassList(), new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Faculty Name</label>
                            @Html.DropDownListFor(model => model.FacultyId, SMS.Utilities.CommonUtilities.GetFacultyList(), new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Section Name</label>
                            @Html.DropDownListFor(model => model.SectionId, SMS.Utilities.CommonUtilities.GetSectionList(), new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Subje Name</label>
                            @Html.DropDownListFor(model => model.SubjectId, SMS.Utilities.CommonUtilities.GetSubjectList(), new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Obtain Theory Marks</label>
                            @Html.TextBoxFor(model => model.ObtainThroryMarks, new { @class="form-control"})
                        </div>
                        <div class="col-sm-6">
                            <label>Obtain Practical Marks</label>
                            @Html.TextBoxFor(model => model.ObtainPracticalMarks, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Remarks</label>
                            @Html.TextBoxFor(model => model.Remarks, new { @class = "form-control" })
                        </div>
                       
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="row">
                    <div class="form-group">
                       

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            }
        </div>
    </div>
</div>

SMS/Views/MarkSheet/Edit.cshtml
@model SMS.Models.MarkSheetViewModel.MarkSheetViewModel
<div class="modal-dialog" style="margin-left:35%">
    <div class="modal-content" style="width:500px!important">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="editMarkSheet">
                Update MarkSheet
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Edit", "MarkSheet", FormMethod.Post))
            {    @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model=>model.MarkSheetId)

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Student Name</label>
                            @Html.DropDownListFor(model => model.StudentId, SMS.Utilities.CommonUtilities.GetStudentList(), new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Terminal Exam Name</label>
                            @Html.DropDownListFor(model => model.TerminalExamId, SMS.Utilities.CommonUtilities.GetTerminalList(), new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Class Name</label>
                            @Html.DropDownListFor(model => model.ClassId, SMS.Utilities.CommonUtilities.GetClassList(), new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Faculty Name</label>
                            @Html.DropDownListFor(model => model.FacultyId, SMS.Utilities.CommonUtilities.GetFacultyList(), new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Section Name</label>
                            @Html.DropDownListFor(model => model.SectionId, SMS.Utilities.CommonUtilities.GetSectionList(), new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Subje Name</label>
                            @Html.DropDownListFor(model => model.SubjectId, SMS.Utilities.CommonUtilities.GetSubjectList(), new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Obtain Theory Marks</label>
                            @Html.TextBoxFor(model => model.ObtainThroryMarks, new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Obtain Practical Marks</label>
                            @Html.TextBoxFor(model => model.ObtainPracticalMarks, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Remarks</label>
                            @Html.TextBoxFor(model => model.Remarks, new { @class = "form-control" })
                        </div>
                        <div class="col-sm-6">
                            <label>Status</label>
                            @Html.CheckBoxFor(model =>model.Status)
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Update" />
                </div>
            }
        </div>
    </div>
</div>

SMS/Views/MarkSheet/Index.cshtml
@model SMS.Models.MarkSheetViewModel.MarkSheetViewModel
@{
    ViewBag.Title = "Faculty List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int i = 1;
}

<link href="~/Content/skins/flat/green.css" rel="stylesheet" />
@if (TempData["validationErro"] != null)
{
    <div class="alert alert-danger">
        @TempData["validationErro"]
    </div>
}

@if (TempData["AlreadyExits"] != null)
{
    <div class="alert alert-danger">
        @TempData["AlreadyExits"]
    </div>
}

@if (TempData["savefailed"] != null)
{
    <div class="alert alert-danger">
        @TempData["savefailed"]
    </div>
}

@if (TempData["save"] != null)
{
    <div class="alert alert-success">
        @TempData["save"]
    </div>
}
<div class="main-content">
    <div class='row r-below-header'>
        <div class='col-md-8 col-sm-12'>
            <div class="r-page-title">
                <h1>
                    Marksheet List
                </h1>
            </div>
        </div>
    </div>
</div>

<input type="button" value="Add New" onclick="addNew('#add-marksheet', 'Create', 'MarkSheet')" class="btn btn-primary" />
<div class="clearfix"></div>
<div class="table table-responsive">
    <table class="table table-striped jambo_table bulk_action">
        <thead>
            <tr class="headings">
                <th><input type="checkbox" class="flat" name="table_records"></th>
                <th class="column-title">S.N.</th>
                <th class="column-title">StudentName </th>
                <th class="column-title">TerminalExamName </th>
                <th class="column-title">SubjectName </th>
                <th class="column-title">ObtainTheoryMark </th>
                <th class="column-title">ObtainPracticalMark </th>
               
                <th class="column-title no-link last">
                    <span class="nobr">Action</span>
                </th>
                <th class="bulk-actions" colspan="7">
                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.MarkSheetViewModelList)
            {
                <tr class="even pointer">
                    <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                    </td>
                    <td>@i</td>
                    <td>@item.StudentName</td>
                    <td>@item.TerminalExamName</td>
                    <td>@item.SubjectName</td>
                    <td>@item.ObtainThroryMarks</td>
                    <td>@item.ObtainPracticalMarks</td>
                    <td>
                        <button class="btn btn-primary" onclick="update(@item.MarkSheetId,'#update-marksheet','Edit','MarkSheet')"><span class="fa fa-edit"></span></button>
                        <button class="btn btn-danger" onclick="deleteRow(@item.MarkSheetId,'@item.SubjectName','Delete','MarkSheet')"><span class="fa fa-trash"></span></button>
                    </td>
                </tr>
                i++;
            }

        </tbody>
    </table>
</div>

<div class="modal fade" id="add-marksheet" tabindex="-1" role="dialog" aria-labelledby="addMarkSheet">
    @{Html.RenderAction("Create", "MarkSheet");}
</div>

<div class="modal fade" id="update-marksheet" tabindex="-1" role="dialog" aria-labelledby="editMarkSheet">
    @{Html.RenderAction("Edit", "MarkSheet");}
</div>
<div class="modal fade" id="delete-conformation" tabindex="-1" role="dialog" aria-labelledby="deleteconformation">
    @{Html.RenderAction("DeleteConformation", "CommonAjaxRequest");}
</div>